name: voter_grievance_redressal
description: A new flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  connectivity: ^0.4.6+2
  rflutter_alert: ^1.0.3
  flutter_svg: ^0.17.1
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.4.0
  google_maps_flutter:
  image_picker:
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
